shamanec/GADS

README.md
device_control.go
helpers.go
static/device_control_new.html

* Moved WDA session creation for iOS device control to Go server instead of web js
* Moved Appium session creation for Android device control to Go server instead of web js
* Cleaned device control js from the now obsolete functions

Move control sessions creation to Go codebase

---

main.go
router/handler.go
util/helpers.go

* Embed the UI static files into the binary
* Unpack the UI static files into a temp or provided folder on app start
* Serve the UI static files from where they were unpacked
This allows us to have a standalone deployable binary without any dependencies on Node or Go on the host machine

UI files folder

---

provider/devices/common.go

It was reported that sometimes Appium uiautomator2 apks fail to reinstall with adb on Linux. Haven't observed it on macOS but just in case all Appium apks will be uninstalled when device setup is started to have a clean slate

Uninstall appium apks in setup

---

provider/devices/common.go

* GADS is meant to be in-house so I see no harm in directly setting relaxed security on the Appium servers started by the `provider`

Set relaxed security on Appium servers

---

common/models/models.go
hub/gads-ui/src/components/Admin/Devices/DevicesAdministration.js
hub/router/appiumgrid.go
hub/router/routes.go
provider/devices/common.go
provider/devices/ios.go
provider/router/routes.go

* Added a button in the Admin panel for re-provisioning device if it gets stuck for some reason
* Make devices fully available after Appium server is up(last step in device provisioning)
* Handle devices in grid better

Add device re-provision button

---

hub/gads-ui/src/components/DeviceControl/StreamCanvas/StreamCanvas.js

* touch&hold in portrait and interactions in landscape on iOS using custom WebDriverAgent were not working due to a bad json key reference

Fix json key reference

---

common/db/db.go

This PR enhances MongoDB connection management by optimizing the connection pool settings for better performance and resource utilization:
Pool Size Configuration:
- Max Pool Size: Set to 200 to handle high-concurrency scenarios efficiently.
- Min Pool Size: Set to 10 to ensure a baseline number of connections are always available.
Connection Management:
- Max Idle Time: Configured to 5 minutes, allowing idle connections to close after inactivity, reducing unnecessary resource consumption.
- These improvements enhance database performance by balancing connection reuse and resource efficiency.

Improve MongoDB Connection Pool Configuration

---

provider/devices/common.go

This update modifies the `startAppium` function to properly format the --default-capabilities parameter by wrapping the JSON string in single quotes. This ensures that the capabilities are correctly parsed when passed to the Appium command.
Command without single quote:
```sh
appium -p 58792 --log-timestamp --session-override --log-no-colors --relaxed-security --default-capabilities {"appium:udid":"DEVICEID","appium:automationName":"UiAutomator2","platformName":"Android","appium:deviceName":"Moto e7"}
```
Output:
```sh
usage: appium server [-h] [--address ADDRESS] [--allow-cors] [--allow-insecure ALLOW_INSECURE] [--base-path BASE_PATH]
[--callback-address CALLBACK_ADDRESS] [--callback-port CALLBACK_PORT] [--debug-log-spacing]
[--default-capabilities DEFAULT_CAPABILITIES] [--deny-insecure …
```

Fix Appium capabilities JSON formatting

---

common/cli/cli.go
go.mod
go.sum
provider/devices/common.go

It is possible that under some conditions the device Appium server process does not get killed and remains, increasing memory consumption on host
* Reset device on disconnect
* When device provisioning start attempt to kill any possibly hanging Appium processes for that device

Handle possibly hanging Appium processes

---

provider/devices/android.go
provider/devices/common.go
provider/router/routes.go

This PR enhances the Android device setup process by introducing a WebSocket-based mechanism to update GADS stream settings dynamically. Key changes include:
- WebSocket Integration for Stream Settings:
- Implemented updateGadsStreamSettings(device), which sends updated stream settings via WebSocket.
- Constructs a message containing targetFPS, jpegQuality, and scalingFactor and transmits it to the device.
- Android Device Setup Enhancement:
- Calls updateGadsStreamSettings(device) after the device is connected to ensure correct streaming parameters.
- Resets the device if updating stream settings fails.

Enable GADS Stream Settings Update via WebSocket

---

common/mutex_manager.go
provider/devices/common.go

This PR ensures thread-safe access when freeing ports in `resetLocalDevice` by introducing a dedicated mutex. Key changes include:
- Added `ResetLocalDeviceFreePorts` Mutex:
- Introduced `ResetLocalDeviceFreePorts` in `ResourceMutexManager` to prevent race conditions.
- Applied `Lock()` and `Unlock()` when modifying providerutil.UsedPorts.
- Improved Port Management in resetLocalDevice:
- Prevented potential concurrency issues when multiple devices are reset simultaneously.
These changes improve stability in multi-threaded environments, ensuring proper resource cleanup.
fixes #160

Fix Concurrent Port Access in resetLocalDevice with Mutex Locking

---

common/mutex_manager.go
provider/devices/common.go
provider/providerutil/providerutil.go

* Use common mutex for allocating ports and removing them from the map on device reset
* Use loop instead of recursion for allocating ports and lock/unlock mutex only when accessing the UsedPorts map

Refactor free port allocation for devices

---

README.md
docs/linux-service.md

This PR enhances the GADS documentation by adding detailed instructions for running the Hub and Provider as system services on Linux. Key additions include:
- Updated README.md:
- Added a new section: "Running GADS as a System Service".
- Linked dedicated documentation for Linux (`docs/linux-service.md`).
- Placeholder sections for Windows and macOS services.
- New Documentation (`docs/linux-service.md`):
- Step-by-step guide for setting up systemd services for both the GADS Hub and Provider.
- Instructions for log rotation using logrotate to prevent excessive log growth.
- Sample configurations for `/etc/systemd/system/gads-hub.service` and `/etc/systemd/system/gads-provider.service`.

Add Documentation for Running GADS as a System Service on Linux

---

provider/logger/logger.go

Modified the `CreateCustomLogger` function to use `io.MultiWriter`, allowing logs to be written to both the log file and the console.

 Enable simultaneous logging to file and console

---

common/models/config.go
common/models/models.go
docs/provider.md
hub/gads-ui/src/components/Admin/Providers/ProvidersAdministration.js
hub/gads-ui/src/components/DeviceControl/DeviceControl.js
hub/gads-ui/src/components/DeviceControl/StreamCanvas/StreamCanvas.js
provider/devices/health.go
provider/devices/ios.go
provider/router/appium.go
provider/router/routes.go

* Remove support for mainstream WebDriverAgent for device remote control
* Remove provider configuration property related to custom WebDriverAgent
* Update readme to include info only about custom WebDriverAgent fork
* Remove button for refreshing Appium session in remote control for iOS devices

Support only custom WebDriverAgent fork

---

common/api/api.go
common/db/stream_settings.go
hub/gads-ui/src/components/DeviceControl/DeviceControl.js
hub/gads-ui/src/components/DeviceControl/StreamCanvas/StreamCanvas.js
hub/gads-ui/src/components/DeviceControl/Tabs/Actions/Apps/UninstallApp.js
hub/gads-ui/src/components/DeviceControl/Tabs/Actions/Clipboard.js
hub/hub.go
provider/devices/android.go
provider/router/appium.go
provider/router/device_routes.go
provider/router/routes.go

* Add the ability to type with your keyboard into focused fields on iOS in remote control
* Improve app uninstall in remote control
* Add generic api response to start streamlining api responses across the project
* Fix typing and getting clipboard on iOS after moving to custom WDA

Add keyboard typing to iOS remote control and improve app uninstall

---

provider/devices/common.go

This PR ensures that the WorkspaceID field in device records is accurately updated during the updateProviderHub process. It fetches the latest device records from the database and synchronizes the WorkspaceID for each device in DBDeviceMap before sending the updated device data to the hub. This fix guarantees consistency between the stored device data and the provider state.
fixes #186

Fix WorkspaceID Sync in Provider Device Update Process

---

hub/router/proxy.go
provider/router/stream.go
provider/router/webrtc_video.go

This PR addresses runtime panics and improves resilience by ensuring all device stream and proxy routes validate the presence of devices before proceeding. Changes include:
- Added nil and existence checks for devices accessed via DBDeviceMap and HubDevicesData.Devices.
- Return HTTP 400 Bad Request responses with clear messages when a device is not found.
- Log detailed error messages using ProviderLogger for traceability.
- Applies across:
- DeviceProxyHandler
- Android/iOS MJPEG stream endpoints
- WebRTC video streaming
- GADS/WDA stream proxies

Fix Missing Device Handling in Stream and Proxy Handlers

---

README.md
common/db/provider.go
common/models/config.go
docs/provider.md
hub/hub.go
hub/router/routes.go
provider/devices/common.go
provider/provider.go
provider/router/control.go
provider/router/routes.go

* Update provider configuration to allow control whether Appium servers should be set up for configured devices
* Add function to update all current providers to set up Appium servers by default so we do not break existing configurations from previous releases
* Update device setup functions to take into account the new provider configuration property
* Add the latest version of the Android GADS Settings app and accommodate the changes

Make Appium optional per provider

---

hub/router/routes.go

This PR resolves a race condition between DeviceInUseWS and DeviceProxyHandler where LastActionTS could be overwritten with an outdated value. By explicitly setting LastActionTS during the WebSocket claim, we ensure the device’s activity timestamp reflects the most recent user interaction reliably

Fix Race Condition by Setting LastActionTS in DeviceInUseWS

---

provider/devices/tizen.go

- Removed assignment of 'device.Name' from 'getTizenTVInfo'
- Prevents erasing user-defined or registered names with remote metadata

Preserve Device Name in Tizen Info Update

---

provider/devices/android.go

This prevents issues with multiple processes trying to bind to port 1994 and ensures only a single RemoteControlServer is active per Android device

Ensure Clean Start of RemoteControlServer

---

common/db/tenant.go
hub/auth/auth.go
hub/hub.go
hub/router/workspace.go

This feature introduces tenant support via a default tenant value that is automatically created and applied across the system.

Add Default Tenant Initialization and Enforce Tenant Field on Workspaces

---

README.md
common/models/appium.go
common/models/config.go
common/models/models.go
docs/provider.md
hub/router/appiumgrid.go
provider/devices/common.go
provider/devices/webos.go
provider/provider.go
provider/providerutil/providerutil.go

- Adds 'ProvideWebOS' to provider config and regularization logic
- Implements 'setupWebOSDevice' to start Appium server with WebOS-specific capabilities
- Includes device detection via 'ares-setup-device --list'
- Updates platform validation logic to restrict WebOS usage to automation only
- Extends documentation: installation, pairing, CLI setup, known limitations
- Updates Appium caps ('deviceHost') and routing detection for WebOS
- Syncs hub-ui submodule to include WebOS support in frontend

Add Support for LG WebOS TVs

---

common/db/workspace.go
hub/router/workspace.go

The GetWorkspaces() endpoint had a pagination bug when filtering by tenant:
- Tenant filtering was happening AFTER pagination instead of before
- This caused missing results when tenant workspaces were distributed across multiple pages
- Example: 6 total workspaces, 3 for specific tenant, with 5 items per page
- One tenant workspace on page 2 would be missing when requesting page 1 with tenant filter
- Only showed 2 workspaces instead of all 3 for that tenant
- Move tenant filtering to database level (MongoDB aggregation pipeline)
- Add `tenant` parameter to `GetWorkspacesWithDeviceCount()` function
- Remove post-query filtering logic from router
- Ensure correct pagination and total count calculation
- **common/db/workspace.go**: Add tenant parameter and database-level filtering
- …

Resolve pagination bug when filtering by tenant
