docker_control.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
main.go
static/android_containers.html
static/index.html
static/ios_containers.html
static/project_config.html
static/project_logs.html

* Removed unnecessary functions and endpoint  
* Updated Swagger docs  
* Added Swagger tab to be able to access Swagger from anywhere in the UI

iOS container creation cleanup

---

Dockerfile
configs/wda-sync.sh

* add small docker cli tool to get WDA url from inside the container

add small docker cli tool

---

configs/wda-sync.sh
devices.go
docker_control.go
main.go
project_control.go
static/android_containers.html
static/device_control.html
static/index.html
static/ios_containers.html
static/project_config.html
static/project_logs.html

* Create a device control page - it does not provide actual m+k control yet  
* Added device selection - choose from running containers  
* Added iOS devices info in the control page like ports, udid etc  
* Embedded mjpeg video stream - can only observe, not interact  
* Added a list of installed iOS apps and button to uninstall selected  
* Created Go functions and endpoints to support all of this

Add Device Control page

---

project_control.go
static/device_control.html

* Add ability to install apps on iOS device from the ones available in './ipa' folder

add ability to install app from available apps

---

static/android_containers.html
static/device_control.html
static/index.html
static/ios_containers.html
static/project_config.html
static/project_config_submission_form.html
static/project_logs.html

* Add a draft for simple device control page showing video stream, allowing simple taps and also query of elements from the Appium server using Appium APIs by Xpath, Class chain etc, display outline of element on canvas similar to Appium Inspector

Add draft of a simple device control page

---

configs/wda-sync.sh
static/device_control.html

* Small updates on control screen

Small updates on control screen

---

devices.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
main.go
static/device_control.html
static/ios_containers.html

Initial code cleanup

---

docker_control.go
main.go

cleanup and improve

---

.gitignore
Dockerfile
README.md
devices.go
docker_control.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
helpers.go
project_control.go

slight code improvements

---

configs/config.json
project_control.go
static/device_control.html

* Connect to existing WDA session or create a new one  
* Added page source tree - ugly and selections are weird but it works  
* Added small table to show element info when selected through page source  
* Added iPhone devices info in the config.json to be able to get device model and screen size without an additional call to WDA

Improve control connection

---

configs/README.md
configs/config.json
configs/ios-sync.sh
docker_control.go
docs/devices-setup.md
main.go
project_control.go

* Added possibility to use usbmuxd per container instead of shared usbmuxd from host  .
* Updated readme  
* Other improvements and changes

Containerized usbmuxd

---

static/device_control_new.html

* Added the ability to take a high quality screenshot from the devices through Appium and display it in the UI. Since the stream quality for Android was decreased after moving to own stream the screenshots will be useful for examining in depth

Add screenshot capability to device control

---

static/device_control_new.html

* iOS jpegs are now sent over ws instead of accessing the WebDriverAgent MJPEG stream directly and the video is built from them

Change iOS stream approach

---

README.md
config.json
main.go
static/device_control_new.html
static/device_selection_new.html
static/index.html
static/project_logs.html
static/selenium_grid.html
util/helpers.go

* Added option to load Selenium Grid in the UI if it is being used

Load Selenium Grid in UI

---

config.json
gads-ui/package-lock.json
gads-ui/package.json
gads-ui/src/Gads.js
gads-ui/src/components/Admin/AddUser.js
gads-ui/src/components/Admin/AdminDashboard.js
gads-ui/src/components/Admin/Provider/Info.js
gads-ui/src/components/Admin/Provider/Provider.js
gads-ui/src/components/Admin/ProvidersAdministration.js
gads-ui/src/components/Admin/UsersAdministration.js
gads-ui/src/components/Common/UploadFile.css
gads-ui/src/components/Common/UploadFile.js
gads-ui/src/components/DeviceControl/DeviceControl.js
gads-ui/src/components/DeviceControl/Tabs/Actions.js
gads-ui/src/components/DeviceControl/Tabs/Screenshot.js
gads-ui/src/components/DeviceControl/Tabs/TabularControl.js
gads-ui/src/components/DeviceControl/TabularControl.js
gads-ui/src/index.css
router/handler.go
router/proxy.go
router/routes.go

* Reworked and extended admin dashboard
* Added option to take screenshot from device
* Added option to upload application file to provider through device control page

Improvements on React UI

---

gads-ui/src/components/DeviceControl/Tabs/Actions/Actions.js

Added a field in the device control page that allows to type whole strings in apps if an input element is selected

Simple type text

---

device/device_control.go
device/device_selection.go
gads-ui/src/components/Admin/AddUser.js
gads-ui/src/components/Admin/ProvidersAdministration.js
gads-ui/src/components/DeviceControl/DeviceControl.js
gads-ui/src/components/DeviceControl/SessionDialogContext.js
gads-ui/src/components/DeviceControl/StreamCanvas.js
gads-ui/src/components/DeviceControl/Tabs/Actions/Actions.js
gads-ui/src/components/DeviceControl/Tabs/Actions/Apps/InstallApp.js
gads-ui/src/components/DeviceControl/Tabs/Actions/Apps/UploadAppFile.js
gads-ui/src/components/DeviceControl/Tabs/Screenshot/Screenshot.js
gads-ui/src/components/DeviceSelection/Device.js
gads-ui/src/components/DeviceSelection/DeviceSelection.js
gads-ui/src/components/Login/Login.js
gads-ui/src/components/TopNavigationBar/TopNavigationBar.js
gads-ui/src/contexts/Auth.js

Some small optimizations on the Auth context and devices list websocket

Optimizations

---

gads-ui/src/components/Admin/Providers/Provider/ProviderConfig.js
gads-ui/src/components/DeviceControl/StreamCanvas.js
gads-ui/src/components/DeviceControl/Tabs/Logs/AppiumLogsTable.js
gads-ui/src/components/DeviceControl/Tabs/TabularControl.js
models/models.go
router/handler.go
router/routes.go

* Added simple log table for Appium logs on the device control view
* Moved away from websocket "video" serving to mjpeg stream

Add Appium log table on device control view

---

common/db/db.go
common/models/config.go
common/models/models.go
docs/hub.md
hub/auth/auth.go
hub/gads-ui/src/components/Admin/Users/AddUser.js
hub/gads-ui/src/components/Login/Login.js
hub/hub.go
hub/router/routes.go
main.go

Stopped using emails for users, now only username and password. For an inhouse solution we don't need some very complex user control for now

Simplify users

---

hub/gads-ui/src/components/Admin/Providers/Provider/Provider.js
hub/gads-ui/src/components/Admin/Providers/Provider/ProviderLogsTable/ProviderLogsTable.js
hub/gads-ui/src/components/Admin/Providers/ProvidersAdministration.js
hub/gads-ui/src/components/ProviderLogsTable/ProviderLogsTable.js
hub/gads-ui/src/components/TopNavigationBar/TopNavigationBar.js
hub/gads-ui/src/contexts/Auth.js
hub/router/handler.go
hub/router/routes.go

* Added logs table for the providers in Admin

Provider logs table

---

common/models/models.go
hub/gads-ui/src/components/Admin/Providers/Provider/ProviderLogsTable/ProviderLogsTable.js
hub/gads-ui/src/components/DeviceControl/Tabs/Actions/Apps/Apps.js
hub/gads-ui/src/components/DeviceControl/Tabs/Actions/Apps/UninstallApp.js
hub/gads-ui/src/components/DeviceControl/Tabs/Actions/Apps/UploadAppFile.js
provider/devices/android.go
provider/devices/common.go
provider/devices/ios.go
provider/logger/appium_logger.go
provider/logger/logger.go
provider/provider.go
provider/providerutil/providerutil.go
provider/router/handler.go
provider/router/routes.go
provider/router/stream.go

* Removed some unused and obsolete code
* Extended logging
* Reworked and combined upload + install app into a single menu and option, no point in storing files around

Cleanup code and change upload and install app aproach

---

hub/gads-ui/package.json
hub/gads-ui/src/Gads.js
hub/gads-ui/src/components/Admin/Providers/Provider/ProviderConfig.js
hub/gads-ui/src/components/Admin/Providers/Provider/ProviderDevice.js
hub/gads-ui/src/components/Admin/Providers/Provider/ProviderLogsTable/ProviderLogsTable.js
hub/gads-ui/src/components/Admin/Providers/ProvidersAdministration.js
hub/gads-ui/src/components/Admin/Users/AddUser.js
hub/gads-ui/src/components/DeviceControl/DeviceControl.js
hub/gads-ui/src/components/DeviceControl/SessionDialogContext.js
hub/gads-ui/src/components/DeviceControl/StreamCanvas.js
hub/gads-ui/src/components/DeviceControl/Tabs/Actions/Actions.js
hub/gads-ui/src/components/DeviceControl/Tabs/Actions/Apps/UninstallApp.js
hub/gads-ui/src/components/DeviceControl/Tabs/Actions/Apps/UploadAppFile.js
hub/gads-ui/src/components/DeviceControl/Tabs/Logs/AppiumLogsTable.js
hub/gads-ui/src/components/DeviceControl/Tabs/Screenshot/Screenshot.js
hub/gads-ui/src/components/DeviceSelection/Device.js
hub/gads-ui/src/components/DeviceSelection/DeviceSelection.js
hub/gads-ui/src/components/Login/Login.js
hub/gads-ui/src/components/TopNavigationBar/TopNavigationBar.js
hub/gads-ui/src/contexts/Auth.js
hub/gads-ui/src/services/api.js
hub/gads-ui/src/services/axios.js
hub/gads-ui/src/services/axiosInterceptor.js

* Add reusable axios client with interceptors to handle authentication
* Updated all API calls to use it

Reusable axios client

---

hub/gads-ui/src/components/DeviceControl/Tabs/Actions/Actions.js
hub/gads-ui/src/components/DeviceControl/Tabs/Actions/Clipboard.js
provider/router/appium.go
provider/router/device_routes.go
provider/router/handler.go

* Add new API endpoint to provider component to get Android and iOS clipboard/pasteboard
* Add in the hub UI a new component for getting and displaying the clipboard/pasteboard value

Get clipboard/pasteboard

---

hub/router/appiumgrid.go
provider/devices/common.go

* Handle all different ways Appium caps might come with the session request - `desiredCapabilities`, `capabilities > firstMatch` and `capabilities > alwaysMatch`

Improve Appium grid

---

common/models/models.go
hub/gads-ui/src/components/DeviceControl/StreamCanvas.js
provider/router/routes.go

* Add basic landscape remote control support

Basic landscape remote control support

---

common/constants/constants.go
common/db/db.go
common/models/models.go
hub/gads-ui/src/components/Admin/Devices/DevicesAdministration.js
hub/gads-ui/src/components/DeviceControl/StreamCanvas.css
hub/gads-ui/src/components/DeviceControl/StreamCanvas.js
hub/router/routes.go
provider/devices/android.go
provider/devices/common.go
provider/devices/ios.go

* Try to automatically add device screen dimensions if they are not provided in the device configuration via the UI
* Change placement of device buttons in control screen

Automatic device screen dimensions

---

docs/faq.md
docs/hub.md
docs/provider.md

- added some separators 
- changed the order 
- fixed links in overview
- added some issues to FAQ
- added some additional information for provider installation to make it less error prone

Reformatting and improvement of docs

---

common/db/db.go

This PR improves the MongoDB connection management by introducing a reconnection mechanism and enhancing error handling:
**Reconnection Logic:**
- Added reconnectMongo function to handle MongoDB reconnection attempts if the connection is lost.
- Automatically retries reconnections with detailed logs for each attempt.
- Resets the error counter when the connection is successfully restored.

Enhance MongoDB Connection Management with Reconnection Logic

---

common/db/db.go

This PR refines the MongoDB connection management logic by:
- Simplified Reconnection:
- Removed the reconnectMongo method, consolidating reconnection attempts within checkDBConnection.
- Integrated timeout handling into checkDBConnection using context.WithTimeout for each Ping operation.
- Timeout and Retry Configuration:
- Introduced maxTimeout to set consistent timeouts for server selection and socket operations.
- Adjusted retry logic to terminate after maxErrorCount failed attempts, enhancing reliability.
- Code Cleanup:
- Updated error logs in GetProvidersFromDB for consistency with provider-related events.

Simplify MongoDB Reconnection Logic and Improve Timeout Management

---

common/db/db.go
common/models/models.go
common/mutex_manager.go
common/sync.go
hub/gads-ui/src/components/Admin/AdminDashboard.js
hub/gads-ui/src/components/Admin/GlobalSettings/GlobalSettings.js
hub/router/handler.go
hub/router/routes.go
provider/devices/common.go
provider/provider.go
provider/router/handler.go
provider/router/routes.go

This PR introduces enhanced management for stream settings, allowing global configurations as well as per-device customizations:
- Global Stream Settings:
- Extended StreamSettings to support platform-specific scaling factors (ScalingFactorAndroid and ScalingFactoriOS).
- Added GlobalSettings tab in the UI (GlobalSettings.js) to manage global configurations via a dedicated admin panel.
- New API endpoints (GET and POST) to retrieve and update global settings.
- Per-Device Stream Settings:
- Added DeviceStreamSettings model and database methods (GetDeviceStreamSettings and UpdateDeviceStreamSettings)  for storing and retrieving custom stream settings.
- Modified setupDevices logic to prioritize per-device settings, with fallback to global configurations.
- Periodic Update Routine:
- …

Implement Per-Device Stream Settings with Global Management

---

docs/provider.md

This PR enhances the provider documentation by:
- Restructuring the "Devices Notes" section to include separate categories for iOS and Android.
- Clarifying instructions for WebDriverAgent preparation, including links to prebuilt versions.
- Improving readability and navigation by updating headings and reorganizing content.
- Fixing minor formatting inconsistencies.

Improve Provider Documentation and WebDriverAgent Setup Instructions

---

provider/devices/common.go

This reverts commit 1b6bbb0935af1a8c30c892504962b64ab41049c6.

Revert "feat(devices): fix Appium capabilities formatting"

---

provider/devices/common.go
provider/logger/appium_logger.go
provider/logger/logger.go

* Capture Appium stderr and print it to provider logs if the command fails
* Fix initial applying of stream settings for iOS devices on device provision
* Truncate local log files on provider start

Bug fixes and improvements

---

provider/devices/common.go
provider/devices/ios.go

This PR improves device reset handling by providing more detailed failure reasons when calling resetLocalDevice(). Key changes include:
- Enhanced Error Logging:
- Modified resetLocalDevice(device) to accept a reason parameter, logging the specific cause of device resets.
- Added contextual failure messages for Android and iOS setup failures (e.g., Appium startup issues, port allocation failures, WebDriverAgent errors).
- Device Setup Improvements:
- Ensured resetLocalDevice() is invoked with a clear explanation of why a device reset is necessary.
- Applied changes across Android and iOS setup functions (setupAndroidDevice, setupIOSDevice).
- Bug Fixes & Logging Updates:
- Fixed incorrect log tags (e.g., "ios_device_setup" incorrectly used in Android setup).

Enhance Device Reset Handling with Detailed Failure Reasons

---

hub/auth/auth.go

This PR improves thread safety in the authentication system by adding a mutex to protect access to the session map. Key changes include:
- Thread-Safe Session Management:
- Introduced sync.Mutex (mapMutex) to prevent race conditions when accessing sessionsMap.
- Locked sessionsMap during login, logout, and authentication checks to ensure consistent state.
- Improved Security & Stability:
- Prevented potential data corruption caused by concurrent access to session data.
- Ensured that session expiration checks and deletions occur safely within the mutex lock.
fixes #156

Fix Concurrent Access to Session Map with Mutex Locking

---

provider/providerutil/providerutil.go

- This update adds comprehensive debug logging to the GetFreePort function in providerutil.
- It logs the steps for resolving the TCP address, listening on the port, and acquiring/releasing locks on used ports.
- Enhanced error logs provide more context when address resolution or port listening fails.

Enhance Logging in GetFreePort for Better Port Allocation Debugging

---

provider/providerutil/providerutil.go

This PR introduces a retry mechanism with an incremental backoff to the GetFreePort function. The function will now attempt to find a free port up to 10 times, with a base backoff of 50ms between attempts. This improves the reliability of port allocation by reducing the chances of immediate failure due to race conditions or transient network issues.

Add retry mechanism with backoff for GetFreePort function

---

README.md

This PR refines the README structure to better communicate GADS's purpose and advantages. The project title now explicitly highlights its role as an open-source device farm. New sections such as "Why Choose GADS?", "Use Cases," and "Project Status" provide clearer insights for users and contributors. Additionally, relevant metadata has been added to improve project discoverability.

Enhance GADS README with structured overview and key benefits

---

provider/devices/common.go

- Refactored processStream to ensure proper handling of multi-line error messages
- Split error messages on newlines to log each line separately
- Improved context cancellation handling by explicitly returning when the device context is canceled
- Enhanced inline comments for better code clarity and maintainability

Improve logging and error handling in Appium processStream

---

common/db/collection.go
common/db/database.go
common/db/db.go
common/db/device.go
common/db/file.go
common/db/generic.go
common/db/log.go
common/db/provider.go
common/db/stream_settings.go
common/db/user.go
common/db/workspace.go
common/models/models.go
hub/auth/auth.go
hub/devices/devices.go
hub/hub.go
hub/router/proxy.go
hub/router/routes.go
hub/router/workspace.go
provider/config/config.go
provider/devices/android.go
provider/devices/common.go
provider/devices/db.go
provider/devices/ios.go
provider/logger/appium_logger.go
provider/logger/logger.go
provider/provider.go
provider/router/routes.go

* Use generics to create reusable read/write functions for MongoDB
* Rework the old db code to use the new structure
* Clean up the unused db code

Improve db code

---

common/db/generic.go
common/db/user.go
common/db/workspace.go
hub/hub.go
hub/router/workspace.go

* Fixed user workspace update, wasn't actually working because upsert was used and User struct includes the user _id from Mongo
* Fixed adding workspace that wasn't working on a new Mongo instance because upsert instead of insert was used with an empty filter
* Fixed getting user workspaces
* Improved device workspace update on hub startup

improve workspace handling

---

.github/workflows/main.yml
README.md
common/models/config.go
docs/hub.md
hub/hub.go
hub/router/handler.go
main.go

* Fix setting WebRTC properties when adding a new Android device configuration
* Add UI files to releases as artifact to potentially allow people to contribute to fixes in the Go code
* Allow using the hub without authentication on the endpoints
* README updates

Improvements, fixes and readme update

---

hub/router/proxy.go
hub/router/routes.go

This PR tightens access control around device usage by verifying session tokens and enforcing exclusivity across users:
🔐 Session Enforcement:
- Both DeviceProxyHandler and DeviceInUseWS:
- Read X-Auth-Token from header or query string.
- Use the session to determine the current user.
- Reject requests (409 Conflict) if the device is in use by another user with a valid session in the last 3 seconds.
related to shamanec/GADS-hub-ui#2

Validate Session Token for Device Proxy and WebSocket Routes

---

provider/devices/common.go
provider/provider.go
provider/providerutil/providerutil.go

* Previously Android MJPEG stream apk was downloaded from Github releases, now it will be part of the released GADS binary to streamline version dependencies

Add Android MJPEG stream apk to binary

---

common/db/workspace.go
common/models/models.go
common/models/responses.go
hub/router/workspace.go

This PR enhances the workspace administration API and UI by adding device count information to each workspace entry.

Add Device Count to Workspace Listing

---

hub/router/appiumgrid.go

This PR refactors the device selection logic used in findAvailableDevice:
- New helper: Adds getTargetOSFromCaps() to infer OS from platformName or automationName
- Cleaner loop: Replaces separate iOS/Android logic with unified filtering based on targetOS

Unify OS Detection from Capabilities and Simplify Device Filtering

---

provider/router/control.go

* Use interaction duration provided from UI for touch& hold

Fix touch and hold for iOS
